/**
 * SafeKrit — regenerate the ITC STP flow documents.
 *
 * Run: npm run plant:flow      (from the repo root)
 *
 * Writes two files into docs/:
 *   itc-stp-pfd.svg      the process flow diagram, one standalone sheet
 *   ITC-STP-FLOW.md      the same flow as mermaid, with the full stream table
 *
 * Both are GENERATED. Nothing in either file is maintained by hand, which is the
 * entire point: a drawing that is edited separately from the model it describes
 * starts lying the first time either changes, and it keeps looking authoritative
 * while it does. Re-run this after any edit to `flowsheet.js` and the documents
 * follow; `itcDiagram.test.js` fails if the generator itself drifts.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const diagram = require('./diagram');
const { buildFlowsheet, buildNodeParams } = require('./flowsheet');
const { IDENTITY } = require('./index');
const { runSteadyState } = require('../../simulation/solver');

const DOCS = path.join(__dirname, '..', '..', '..', '..', 'docs');

/** `| a | b |` with pipes in cell text escaped, so a table cannot break. */
const row = (cells) => `| ${cells.map((c) => String(c == null ? '—' : c).replace(/\|/g, '\\|')).join(' | ')} |`;

function buildMarkdown(model, results) {
  const table = diagram.streamTable(model);
  const services = [...new Set(table.map((r) => r.service))];
  const out = [];

  out.push('# ITC Sewage Treatment Plant — process flow');
  out.push('');
  out.push('> **Generated.** Do not edit this file by hand — run `npm run plant:flow`.');
  out.push('> Every block, line and number below is derived from');
  out.push('> `backend/src/plants/itcStp/flowsheet.js`, so the drawing cannot say anything');
  out.push('> the plant model does not.');
  out.push('');
  out.push(`Client **${IDENTITY.client}** · Contractor **${IDENTITY.contractor}** · Sub-contractor **${IDENTITY.subContractor}**`);
  out.push('');
  out.push(`Design flow **${model.designFlowKld} KLD** · ${model.blocks.length} unit operations · ${model.streams.length} streams`);
  out.push('');
  out.push('The sheet below is a **PFD, not a P&ID**: valves and instruments are summarised');
  out.push('on the line they sit on, because they belong on the P&ID and all 339 of them are');
  out.push('already specified in the I/O schedule. Flows are the steady-state solution, not');
  out.push('nameplate figures.');
  out.push('');
  out.push('A printable version of the same sheet: [`itc-stp-pfd.svg`](itc-stp-pfd.svg).');
  out.push('');

  out.push('## The flow');
  out.push('');
  out.push('```mermaid');
  out.push(diagram.toMermaid(model));
  out.push('```');
  out.push('');

  out.push('## Stream table');
  out.push('');
  out.push('Keyed to the circled numbers on the SVG sheet.');
  out.push('');
  out.push(row(['#', 'From', 'To', 'Service', 'Size', 'm³/d', 'TSS', 'BOD', 'TN', 'TP', 'pH', 'In line']));
  out.push(row(['--:', '---', '---', '---', '--:', '--:', '--:', '--:', '--:', '--:', '--:', '---']));
  for (const r of table) {
    out.push(row([r.no, r.from, r.to, r.service, r.size, r.Q_m3_d, r.TSS, r.BOD, r.TN, r.TP, r.pH, r.inlineEquipment]));
  }
  out.push('');

  out.push('## Services');
  out.push('');
  out.push(row(['Service', 'Streams', 'Total m³/d']));
  out.push(row(['---', '--:', '--:']));
  for (const s of services) {
    const rows = table.filter((r) => r.service === s);
    const total = rows.reduce((a, r) => a + (r.Q_m3_d || 0), 0);
    out.push(row([s, rows.length, total ? total.toFixed(1) : '—']));
  }
  out.push('');

  if (model.assumptions.length) {
    out.push('## Assumed parameters');
    out.push('');
    out.push(`${model.assumptions.length} blocks on this sheet carry a value the proposal does not state.`);
    out.push('They are marked **(A)** on the SVG. Everything else is a stated duty.');
    out.push('');
    out.push(row(['Block', 'Assumption']));
    out.push(row(['---', '---']));
    for (const a of model.assumptions) out.push(row([`\`${a.tag}\``, a.text]));
    out.push('');
  }

  const boundaries = results && results.summary && results.summary.boundaries;
  if (boundaries) {
    out.push('## Plant balance');
    out.push('');
    out.push(row(['Boundary', 'Type', 'm³/d', 'Graded']));
    out.push(row(['---', '---', '--:', '---']));
    out.push(row(['**Influent (3 sources)**', 'in', results.summary.influent.Q.toFixed(1), '—']));
    for (const b of boundaries) {
      out.push(row([b.label, b.dischargeType, b.Q.toFixed(1), b.graded ? 'yes' : 'no']));
    }
    out.push('');
    const unrouted = results.summary.unroutedLosses || [];
    if (unrouted.length) {
      out.push(`Plus ${unrouted.length} unrouted side stream(s) counted as plant-boundary losses: `
        + `${unrouted.map((u) => `${u.stream} from \`${u.node}\` (${u.Q_m3_d} m³/d)`).join(', ')}.`);
      out.push('');
    }
  }

  return out.join('\n');
}

function main() {
  const canvas = buildFlowsheet();
  const results = runSteadyState(canvas, { nodeParams: buildNodeParams() });
  const model = diagram.buildDiagram({ results });

  fs.mkdirSync(DOCS, { recursive: true });

  const svgPath = path.join(DOCS, 'itc-stp-pfd.svg');
  fs.writeFileSync(svgPath, diagram.toSvg(model), 'utf8');

  const mdPath = path.join(DOCS, 'ITC-STP-FLOW.md');
  fs.writeFileSync(mdPath, `${buildMarkdown(model, results)}\n`, 'utf8');

  console.log(`  ✔  ${path.relative(process.cwd(), svgPath)}  (${model.blocks.length} blocks, ${model.streams.length} streams, ${model.geometry.width}×${model.geometry.height})`);
  console.log(`  ✔  ${path.relative(process.cwd(), mdPath)}`);
  if (!results.converged) console.warn('  ⚠  the flow did not converge — the stream table is not a balance');
  for (const w of results.warnings || []) console.log(`     · ${w}`);
}

if (require.main === module) main();

module.exports = { buildMarkdown, main };
